"""Hardware regression for PWM generated by the FPGA Bit Engine."""
import sys
import struct

sys.path.insert(0, ".")
from driver.ols_spi_device import OLSDeviceSPI


def transitions(samples):
    words = struct.unpack(f"<{len(samples) // 2}H", samples[:len(samples) & ~1])
    bits = [(sample >> 0) & 1 for sample in words]
    return sum(a != b for a, b in zip(bits, bits[1:]))


dev = OLSDeviceSPI()
dev.open()
try:
    dev.reset()
    dev.set_bitbang_pwm(True, freq_hz=100_000, duty_pct=50, cycles=32)
    samples = dev.capture(rate_hz=1_000_000, nsamples=4096)
    tr_on = transitions(samples)
    assert tr_on >= 8, f"Bit Engine PWM produced too few transitions: {tr_on}"
    print(f"PASS: Bit Engine PWM transitions = {tr_on}")
finally:
    try:
        dev.set_bitbang_pwm(False)
    finally:
        dev.close()
