"""Hardware regression for PWM generated by the FPGA Bit Engine."""
import sys
import struct

sys.path.insert(0, ".")
from driver.ols_spi_device import OLSDeviceSPI


def transitions(samples):
    words = struct.unpack(f"<{len(samples) // 2}H", samples[:len(samples) & ~1])
    bits = [(sample >> 0) & 1 for sample in words]
    return sum(a != b for a, b in zip(bits, bits[1:]))


dev = OLSDeviceSPI()
dev.open()
try:
    dev.reset()
    symbol_rate = 3_200_000
    period = 32
    symbols = ([1] * 16 + [0] * 16) * 32
    samples = dev.capture_with_gen(
        rate_hz=1_000_000, nsamples=4096, raw_symbols=symbols,
        raw_symbol_rate=symbol_rate, raw_tx_pin=0, fast_mode=False)
    tr_on = transitions(samples)
    assert tr_on >= 8, f"Bit Engine PWM produced too few transitions: {tr_on}"
    print(f"PASS: Bit Engine PWM transitions = {tr_on}")
finally:
    try:
        dev.pkt.transaction(0x11, timeout=0.5)
    finally:
        dev.close()
